export interface Game {
  id: string
  name: string
  shortName: string
  image: string
  color: string
  description: string
  status: 'live' | 'coming-soon'
  characterCount?: number
  comboCount?: number
}

export const GAMES: Game[] = [
  {
    id: 'league',
    name: 'League of Legends',
    shortName: 'LoL',
    image: '/images/games/league.jpg',
    color: '#C89B3C',
    description: '150 champions, 794 combos with video timing',
    status: 'live',
    characterCount: 150,
    comboCount: 794,
  },
  {
    id: 'ggst',
    name: 'Guilty Gear -Strive-',
    shortName: 'GGST',
    image: '/images/games/ggst.jpg',
    color: '#E83535',
    description: '34 characters, 898 combos from Dustloop',
    status: 'live',
    characterCount: 34,
    comboCount: 898,
  },
  {
    id: 'bbcf',
    name: 'BlazBlue: Central Fiction',
    shortName: 'BBCF',
    image: '',
    color: '#2962FF',
    description: '37 characters, 2,104 combos from Dustloop',
    status: 'live',
    characterCount: 37,
    comboCount: 2104,
  },
  {
    id: 'bbtag',
    name: 'BlazBlue Cross Tag Battle',
    shortName: 'BBTag',
    image: '',
    color: '#7C4DFF',
    description: '54 characters, 1,371 combos from Dustloop',
    status: 'live',
    characterCount: 54,
    comboCount: 1371,
  },
  {
    id: 'dbfz',
    name: 'Dragon Ball FighterZ',
    shortName: 'DBFZ',
    image: '/images/games/dbfz.jpg',
    color: '#FF9800',
    description: '46 characters, 1,222 combos from Dustloop',
    status: 'live',
    characterCount: 46,
    comboCount: 1222,
  },
  {
    id: 'gbvsr',
    name: 'Granblue Fantasy Versus: Rising',
    shortName: 'GBVSR',
    image: '',
    color: '#00BCD4',
    description: '43 characters, 594 combos from Dustloop',
    status: 'live',
    characterCount: 43,
    comboCount: 594,
  },
  {
    id: 'ggxrd',
    name: 'Guilty Gear Xrd REV 2',
    shortName: 'GGXrd',
    image: '',
    color: '#FF1744',
    description: '26 characters, 816 combos from Dustloop',
    status: 'live',
    characterCount: 26,
    comboCount: 816,
  },
  {
    id: 'ggacr',
    name: 'Guilty Gear XX AC+R',
    shortName: 'AC+R',
    image: '',
    color: '#D50000',
    description: '13 characters, 669 combos from Dustloop',
    status: 'live',
    characterCount: 13,
    comboCount: 669,
  },
  {
    id: 'dnfd',
    name: 'DNF Duel',
    shortName: 'DNFD',
    image: '',
    color: '#4CAF50',
    description: '22 characters, 132 combos from Dustloop',
    status: 'live',
    characterCount: 22,
    comboCount: 132,
  },
  {
    id: 'p4au',
    name: 'Persona 4 Arena Ultimax',
    shortName: 'P4AU',
    image: '',
    color: '#FFEB3B',
    description: '22 characters, 249 combos from Dustloop',
    status: 'live',
    characterCount: 22,
    comboCount: 249,
  },
  {
    id: 'sf6',
    name: 'Street Fighter 6',
    shortName: 'SF6',
    image: '/images/games/sf6.jpg',
    color: '#E2342D',
    description: 'Coming soon — frame data from community sources',
    status: 'coming-soon',
  },
  {
    id: 'tekken8',
    name: 'Tekken 8',
    shortName: 'T8',
    image: '/images/games/tekken8.jpg',
    color: '#FF6B00',
    description: 'Coming soon — Wavu Wiki data',
    status: 'coming-soon',
  },
  {
    id: 'mk1',
    name: 'Mortal Kombat 1',
    shortName: 'MK1',
    image: '/images/games/mk1.jpg',
    color: '#F5C518',
    description: 'Coming soon — kombos with timing',
    status: 'coming-soon',
  },
  {
    id: 'smash',
    name: 'Super Smash Bros. Ultimate',
    shortName: 'SSBU',
    image: '/images/games/smash.jpg',
    color: '#E60012',
    description: 'Coming soon — true combos and kill confirms',
    status: 'coming-soon',
  },
]
